#db_backup Script Config

#db
db:
  user: user
  password: pass

#backup
num_backup_stored: 5

#local_storage
local_enable: true
local_folder: .\backup  # Without final slash

#ftp
ftp_enable: false
ftp_servers: []
# - address: first address
#   user:
#   password:
# - address: second address
#   user:
#   password: