#db_backup Script Config

#db
db_user: user
db_password: pass

#backup
num_backup_stored: 5

#local_storage
local_enable: true
local_folder: .\backup  # Without final slash

#ftp
ftp_enable: false
ftp_servers: []
# - ftp_address: first address
#   ftp_user:
#   ftp_password:
# - ftp_address: second address
#   ftp_user:
#   ftp_password: