class ConvertDbToUtf8mb4 < ActiveRecord::Migration
  def change
    config = Rails.configuration.database_configuration

    # database
    execute('ALTER DATABASE ' + config[Rails.env]["database"] + ' CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    
    # tables
    execute('ALTER TABLE hat_requests DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE messages DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE votes DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitation_requests DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE taggings DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE tags DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE keystores DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitations DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE moderations DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE hidden_stories DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE hats DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE comments DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE read_ribbons DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE suggested_taggings DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE tag_filters DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE schema_migrations DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE suggested_titles DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    
    # columns
    execute('ALTER TABLE hat_requests CHANGE hat hat varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE hat_requests CHANGE link link varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE hat_requests CHANGE comment comment text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE messages CHANGE subject subject varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE messages CHANGE body body mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE messages CHANGE short_id short_id varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE votes CHANGE reason reason varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitation_requests CHANGE code code varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitation_requests CHANGE email email varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitation_requests CHANGE name name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitation_requests CHANGE memo memo text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitation_requests CHANGE ip_address ip_address varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE tags CHANGE tag tag varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE tags CHANGE description description varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    # execute('ALTER TABLE keystores CHANGE key key varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitations CHANGE email email varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitations CHANGE code code varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE invitations CHANGE memo memo mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE moderations CHANGE action action mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE moderations CHANGE reason reason mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories CHANGE url url varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories CHANGE title title varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories CHANGE description description longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories CHANGE short_id short_id varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories CHANGE markeddown_description markeddown_description longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories CHANGE story_cache story_cache longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE stories CHANGE twitter_id twitter_id varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE hats CHANGE hat hat varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE hats CHANGE link link varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE username username varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE email email varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE password_digest password_digest varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE password_reset_token password_reset_token varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE session_token session_token varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE about about mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE rss_token rss_token varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE mailing_list_token mailing_list_token varchar(75) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE banned_reason banned_reason varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE disabled_invite_reason disabled_invite_reason varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE users CHANGE settings settings text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE comments CHANGE short_id short_id varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE comments CHANGE comment comment mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE comments CHANGE markeddown_comment markeddown_comment mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE schema_migrations CHANGE version version varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
    execute('ALTER TABLE suggested_titles CHANGE title title varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;')
  end
end
